[project]
name = "pytorch-realtime-stock-forecaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masroor Amir", email = "masrooramir76@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
pytorch-realtime-stock-forecaster = "pytorch_realtime_stock_forecaster:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
